import sys
import os
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__) + '/../'))
from tools.revenue_tracker import queue_content

if __name__ == "__main__":
    test_piece = [{
        "platform": "facebook",
        "content_type": "post",
        "title": "AI Phone Guy Test Post",
        "body": "This is a live test post for AI Phone Guy, generated by the pipeline.",
        "hashtags": "#AI #PhoneGuy #Test",
        "cta": "Call now for your AI phone demo!",
        "funnel_stage": "awareness"
    }]
    queued = queue_content("aiphoneguy", "zoe", test_piece)
    print(f"Queued: {queued}")
