"""tools/sofia_tools.py — CrewAI tool wrappers for Sofia's creative + queue surface.

Sofia (Head of Content & Creative at Calling Digital) needs three things at
runtime that the lower-level modules expose as plain Python functions:
  1. Image generation     (tools/image_gen.generate_image)
  2. Video generation     (tools/video_gen.generate_video)
  3. Social-post drafting (tools/zernio.create_zernio_draft)

This module wraps those functions as CrewAI @tool callables so Sofia can call
them mid-Crew. It also exposes a queue_for_approval tool so Sofia can submit
a finished post (caption + image + schedule + platform) directly into the
approval queue, where it is picked up by the weekly digest service and sent
to the client for review.

Errors return as strings (matches web_search_tool / tools/keyapi.py /
tools/shopify.py / tools/klaviyo.py pattern) — the LLM gets useful feedback
instead of a crashed Crew.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from crewai.tools import tool

logger = logging.getLogger(__name__)


def _split_csv(s: str) -> list[str]:
    if not s:
        return []
    return [x.strip() for x in s.split(",") if x.strip()]


def _truncate_json(obj: Any, max_chars: int = 4000) -> str:
    out = json.dumps(obj, indent=2, default=str)
    if len(out) > max_chars:
        out = out[:max_chars] + "\n\n[...truncated for context budget...]"
    return out


# ---------------------------------------------------------------------------
# Media generation
# ---------------------------------------------------------------------------

@tool("Generate Social Image")
def sofia_generate_image(
    prompt: str,
    business_key: str = "calling_digital",
    platform: str = "instagram",
    aspect_ratio: str = "",
) -> str:
    """Generate a social-media image via Replicate FLUX.

    Use this when drafting a static IG / Facebook post, a quote card, or a
    lifestyle product shot. The returned URL can then be attached to a
    Zernio draft or saved into an artifact's metadata.image_url field.

    Args:
        prompt: Visual description of the image (e.g., 'Hardcover spiral
            journal with watercolor butterflies on a linen tablecloth, soft
            natural light, neutral palette').
        business_key: Tenant key for any brand-specific style prefixing.
            Default 'calling_digital'.
        platform: Target platform — affects default aspect ratio. Defaults
            to 'instagram' (1:1). Use 'instagram_story' for 9:16, 'facebook'
            for 1:1, 'tiktok' for 9:16.
        aspect_ratio: Override aspect ratio (e.g. '1:1', '9:16', '4:5').
            Empty = use platform default.

    Returns: JSON string with `urls`, `model`, `aspect_ratio`, `prompt_used`
        on success; error string on failure.
    """
    prompt = (prompt or "").strip()
    if not prompt:
        return "ERROR: prompt is required."
    try:
        from tools.image_gen import generate_image
        result = generate_image(
            prompt=prompt,
            business_key=business_key or "",
            platform=platform or "default",
            aspect_ratio=aspect_ratio or "",
        )
        return _truncate_json(result)
    except Exception as e:
        logger.exception("sofia_generate_image failed")
        return f"ERROR: image generation failed: {type(e).__name__}: {e}"


@tool("Generate Social Video")
def sofia_generate_video(
    prompt: str,
    business_key: str = "calling_digital",
    platform: str = "instagram_reel",
    duration: int = 0,
    start_image_url: str = "",
) -> str:
    """Generate a short-form video clip via Replicate (Kling / MiniMax).

    Use this for IG Reels, TikTok, and short Facebook videos. Optionally
    pass start_image_url to do image-to-video (e.g., animate a journal
    cover shot generated by sofia_generate_image).

    Args:
        prompt: Description of the desired video content.
        business_key: Tenant key. Default 'calling_digital'.
        platform: 'instagram_reel', 'tiktok', or 'facebook' control duration
            + aspect ratio defaults.
        duration: Clip length in seconds. 0 = platform default.
        start_image_url: Optional first-frame image URL.

    Returns: JSON string with `url`, `model`, `aspect_ratio`, `duration`,
        `prompt_used` on success; error string on failure.
    """
    prompt = (prompt or "").strip()
    if not prompt:
        return "ERROR: prompt is required."
    try:
        from tools.video_gen import generate_video
        result = generate_video(
            prompt=prompt,
            business_key=business_key or "",
            platform=platform or "default",
            duration=int(duration) if duration else 0,
            start_image_url=start_image_url or None,
        )
        return _truncate_json(result)
    except Exception as e:
        logger.exception("sofia_generate_video failed")
        return f"ERROR: video generation failed: {type(e).__name__}: {e}"


# ---------------------------------------------------------------------------
# Social drafting (Zernio)
# ---------------------------------------------------------------------------

@tool("Create Zernio Social Draft")
def sofia_create_zernio_draft(
    content: str,
    platforms: str,
    media_urls: str = "",
) -> str:
    """Create a draft social post in Zernio. Draft only — does NOT publish.

    The draft sits in Zernio until an artifact is dispatched (which happens
    only after Miriam approves the post in the weekly digest).

    Args:
        content: Post caption / text body.
        platforms: Comma-separated platform list (e.g. 'instagram,tiktok').
            Supported: instagram, tiktok, facebook, linkedin, twitter,
            youtube, pinterest, threads, bluesky.
        media_urls: Optional comma-separated list of media URLs (image or
            video). Auto-detects type from extension.

    Returns: JSON string with the draft post object (id, status) on success;
        error string on failure.
    """
    content = (content or "").strip()
    if not content:
        return "ERROR: content is required."
    plats = _split_csv(platforms)
    if not plats:
        return "ERROR: at least one platform is required."

    try:
        from tools.zernio import create_zernio_draft
        media = _split_csv(media_urls) or None
        result = create_zernio_draft(content=content, platforms=plats, media_urls=media)
        return _truncate_json(result)
    except Exception as e:
        logger.exception("sofia_create_zernio_draft failed")
        return f"ERROR: Zernio draft failed: {type(e).__name__}: {e}"


# ---------------------------------------------------------------------------
# Approval queue intake
# ---------------------------------------------------------------------------

@tool("Queue Post for Client Approval")
def sofia_queue_for_approval(
    business_key: str,
    subject: str,
    content: str,
    platforms: str,
    intent: str = "inform",
    image_url: str = "",
    video_url: str = "",
    scheduled_for: str = "",
    confidence: float = 0.85,
) -> str:
    """Queue a finished post into the approval queue for the weekly digest.

    Sofia calls this once a piece of content is fully drafted (caption +
    media URL + schedule). The artifact lands in pending_approval status,
    surfaces in the next Sunday 6 PM CT digest email to the client, and only
    publishes after the client taps Approve.

    Args:
        business_key: Tenant key (e.g. 'paper_and_purpose').
        subject: One-line headline / internal title for the digest item
            (e.g. 'IG Reel + TikTok cross-post: launch teaser').
        content: The actual post copy (caption + hashtags).
        platforms: Comma-separated channel list (e.g. 'instagram,tiktok').
        intent: One of inform / educate / nurture / close / retain / alert.
            Default 'inform'.
        image_url: Optional preview image URL — shown inline in the digest.
        video_url: Optional video URL — referenced in metadata.
        scheduled_for: Human-readable schedule (e.g. 'Tue, Sep 8 2026 — 7:08 AM CT').
        confidence: Self-assessed confidence 0–1. Default 0.85.

    Returns: JSON string with the queued artifact_id on success; error string
        on failure.
    """
    business_key = (business_key or "").strip()
    subject = (subject or "").strip()
    content = (content or "").strip()
    if not (business_key and subject and content):
        return "ERROR: business_key, subject, and content are all required."
    plats = _split_csv(platforms)
    if not plats:
        return "ERROR: at least one platform is required in platforms."

    try:
        from services.artifact import create_artifact
        from services.approval_queue import queue_artifact

        metadata: dict[str, Any] = {
            "platform": ", ".join(plats),
            "scheduled_for": scheduled_for or "",
        }
        if image_url:
            metadata["image_url"] = image_url
        if video_url:
            metadata["video_url"] = video_url

        # IMPORTANT: every client-facing social post Sofia queues must go
        # through the approval digest gate to reach Miriam. We explicitly
        # set risk_level="medium" so the artifact lands in pending_approval
        # status regardless of confidence — high-confidence content does NOT
        # bypass the client-approval gate. This is a hard rule of the
        # Calling Digital agency model: clients approve every post.
        artifact = create_artifact(
            agent_id="sofia",
            business_key=business_key,
            artifact_type="social_post",
            audience="public",
            intent=intent,
            content=content,
            subject=subject,
            channel_candidates=plats,
            confidence=float(confidence),
            risk_level="medium",
            metadata=metadata,
        )
        artifact_id = queue_artifact(artifact)
        return _truncate_json({
            "ok": True,
            "artifact_id": artifact_id,
            "business_key": business_key,
            "status": artifact.status,
            "risk_level": artifact.risk_level,
            "subject": subject,
        })
    except Exception as e:
        logger.exception("sofia_queue_for_approval failed")
        return f"ERROR: queue failed: {type(e).__name__}: {e}"


SOFIA_CREATIVE_TOOLS = [
    sofia_generate_image,
    sofia_generate_video,
    sofia_create_zernio_draft,
    sofia_queue_for_approval,
]
